[project]
name = "agent-ctl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "redjax", email = "no@none.com" }
]
requires-python = ">=3.11"
dependencies = [
    "database-lib",
    "dynaconf>=3.2.6",
    "http-lib",
    "loguru>=0.7.3",
    "pydantic>=2.10.5",
    "settings-lib",
    "setup-lib",
]

[project.scripts]
agent-ctl = "agent_ctl:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
http-lib = { workspace = true }
database-lib = { workspace = true }
setup-lib = { workspace = true }
settings-lib = { workspace = true }
